version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - literature_network
    restart: unless-stopped
    # Не открываем порт наружу в продакшене
    # ports:
    #   - "5432:5432"

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.production
    environment:
      NODE_ENV: production
    env_file:
      - ./server/.env.production
    depends_on:
      - postgres
    networks:
      - literature_network
    restart: unless-stopped
    # Внутренний порт для nginx
    expose:
      - "3001"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.production
    env_file:
      - ./client/.env.production
    networks:
      - literature_network
    restart: unless-stopped
    # Внутренний порт для nginx
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - server
      - client
    networks:
      - literature_network
    restart: unless-stopped

volumes:
  postgres_prod_data:

networks:
  literature_network:
    driver: bridge