version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env.production
    depends_on:
      - postgres
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://your-server-ip:3001
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    restart: unless-stopped

volumes:
  postgres_data: