services:
  - type: web
    name: literature-locations-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  - type: web
    name: literature-locations-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: literature-locations-db
    databaseName: literature_locations
    user: lit_admin